use super::CompileErrorKind;

impl CompileErrorKind {
    pub fn annotation(&self) -> &'static str {
        match self {
            Self::UndefinedVariable(_) => "not found in this scope",
            Self::VariableAlreadyDefined(_) => "already defined here",
            Self::AssignToImmutable(_) => "variable is not mutable",
            Self::AssignToLoopVariable(_) => "'i' is controlled by the for loop",
            Self::InvalidAssignmentTarget => "cannot assign to this",
            Self::NullIsNotInSurface => "choose Option or Result",
            Self::ExpectedPattern => "match arm starts here",
            Self::InvalidPattern { .. } => "pattern is not valid here",
            Self::UnknownVariant { .. } => "variant is not in this sum type",
            Self::MatchArmValueRequired => "no arm value found",
            Self::RecursionDepthExceeded { .. } => "nesting limit exceeded",
            Self::CommentNestingTooDeep { .. } => "nesting limit exceeded",
            Self::UnexpectedToken { .. } => "unexpected token",
            Self::ReturnOutsideFunction => "not inside a function",
            Self::MissingReturnValue { .. } => "a reachable path has no value",
            Self::IntegerOverflow { .. } => "value exceeds range",
            Self::ModuleNotFound { .. } => "module not found",
            Self::CircularDependency { .. } => "creates circular dependency",
            Self::SymbolNotPublic { .. } => "symbol is not public",
            Self::StdlibNotAvailable { .. } => "'std' modules are not yet implemented",
            Self::SymbolNotFound { .. } => "symbol not found",
            Self::InvalidNativeModule { .. } => "invalid native module",
            Self::NativeChecksumMismatch { .. } => "checksum mismatch",
            Self::NativeVersionMismatch { .. } => "version constraint not satisfied",
            Self::ModulePathSeparator { .. } => "use the module path separator",
            Self::NonExhaustiveMatch { .. } => "match must cover every variant",
            Self::IgnoredResult => "this Result is discarded",
            Self::IgnoredOption => "this Option is discarded",
            Self::QuestionMarkOutsideResult => "no result type to propagate",
            Self::QuestionMarkTypeMismatch { .. } => "error types cannot be converted",
            Self::UnresolvedSumType { .. } => "type information is missing",
            Self::UntypedSumValue { .. } => "native value has no Aelys signature",
            Self::InvalidSumMethod { .. } => "method does not belong to this sum",
            Self::DynamicSumMethod { .. } => "dynamic type has no sum semantics",
            Self::TypeInferenceError(_) => "type inference failed",
            Self::NamedTypeError { .. } => "the type checker rejected this program",
            _ => "",
        }
    }
}
