use super::CompileErrorKind;

impl CompileErrorKind {
    pub fn code(&self) -> u16 {
        match self {
            Self::UnterminatedString => 1,
            Self::InvalidCharacter(_) => 2,
            Self::InvalidNumber(_) => 3,
            Self::InvalidEscape(_) => 5,
            Self::UnterminatedFmtExpr => 6,
            Self::UnmatchedCloseBrace => 7,
            Self::UnexpectedToken { .. } => 101,
            Self::ExpectedExpression => 102,
            Self::ExpectedIdentifier => 103,
            Self::InvalidAssignmentTarget => 104,
            Self::NullIsNotInSurface => 106,
            Self::ExpectedPattern => 107,
            Self::InvalidPattern { .. } => 108,
            Self::UnknownVariant { .. } => 109,
            Self::MatchArmValueRequired => 110,
            Self::RecursionDepthExceeded { .. } => 105,
            Self::CommentNestingTooDeep { .. } => 4,
            Self::TypeNestingTooDeep { .. } => 380,
            Self::BorrowingReceiverDeferred { .. } => 111,
            Self::TraitObjectDeferred { .. } => 113,
            Self::NegativeImplDeferred => 114,
            Self::SpecializationDeferred => 115,
            Self::UndefinedVariable(_) => 201,
            Self::VariableAlreadyDefined(_) => 202,
            Self::AssignToImmutable(_) => 203,
            Self::TooManyConstants => 204,
            Self::TooManyRegisters => 205,
            Self::TooManyArguments => 206,
            Self::TooManyUpvalues => 211,
            Self::JumpOffsetTooLarge { .. } => 213,
            Self::CompilationLimitExceeded(_) => 214,
            Self::BreakOutsideLoop => 207,
            Self::ContinueOutsideLoop => 208,
            Self::ReturnOutsideFunction => 212,
            Self::MissingReturnValue { .. } => 215,
            Self::AssignToLoopVariable(_) => 210,
            Self::IntegerOverflow { .. } => 209,
            Self::ModuleNotFound { .. } => 401,
            Self::CircularDependency { .. } => 402,
            Self::SymbolNotPublic { .. } => 403,
            Self::StdlibNotAvailable { .. } => 404,
            Self::SymbolNotFound { .. } => 405,
            Self::InvalidNativeModule { .. } => 406,
            Self::NativeChecksumMismatch { .. } => 408,
            Self::NativeVersionMismatch { .. } => 409,
            Self::SymbolConflict { .. } => 410,
            Self::TypeNotExportable { .. } => 407,
            Self::ModulePathSeparator { .. } => 411,
            Self::PrivateFieldAccess(..) => 412,
            Self::PrivateFieldConstruction(..) => 413,
            Self::NonExhaustiveMatch { .. } => 302,
            Self::IgnoredResult => 303,
            Self::IgnoredOption => 304,
            Self::QuestionMarkOutsideResult => 305,
            Self::QuestionMarkTypeMismatch { .. } => 306,
            Self::UnresolvedSumType { .. } => 307,
            Self::UntypedSumValue { .. } => 308,
            Self::InvalidSumMethod { .. } => 309,
            Self::DynamicSumMethod { .. } => 310,
            Self::TypeInferenceError(_) => 301,
            Self::NamedTypeError { code, .. } => *code,
        }
    }
}
